//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocsManagerWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocsManagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocsManagerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocsManagerWebApp.Resources.DocsManagerResources", typeof(DocsManagerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc file type.
        /// </summary>
        public static string DocFileName {
            get {
                return ResourceManager.GetString("DocFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created in application.
        /// </summary>
        public static string DocumentApplication_tableLabel {
            get {
                return ResourceManager.GetString("DocumentApplication_tableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created in company.
        /// </summary>
        public static string DocumentCompany_tableLabel {
            get {
                return ResourceManager.GetString("DocumentCompany_tableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created.
        /// </summary>
        public static string DocumentCreationDate_tableLabel {
            get {
                return ResourceManager.GetString("DocumentCreationDate_tableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document manager.
        /// </summary>
        public static string DocumentManager_tableLabel {
            get {
                return ResourceManager.GetString("DocumentManager_tableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to docx file type.
        /// </summary>
        public static string DocxFileName {
            get {
                return ResourceManager.GetString("DocxFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file created successfully.
        /// </summary>
        public static string FileCreated_message {
            get {
                return ResourceManager.GetString("FileCreated_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file name.
        /// </summary>
        public static string FileName_tableLabel {
            get {
                return ResourceManager.GetString("FileName_tableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file removed successfully.
        /// </summary>
        public static string FileRemoved_message {
            get {
                return ResourceManager.GetString("FileRemoved_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file size.
        /// </summary>
        public static string FileSize_tableLabel {
            get {
                return ResourceManager.GetString("FileSize_tableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file removed.
        /// </summary>
        public static string FilesRemovedMessage_fileupload_label {
            get {
                return ResourceManager.GetString("FilesRemovedMessage_fileupload_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files uploaded.
        /// </summary>
        public static string FilesUploadedMessage_fileupload_label {
            get {
                return ResourceManager.GetString("FilesUploadedMessage_fileupload_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file type.
        /// </summary>
        public static string FileType_tableLabel {
            get {
                return ResourceManager.GetString("FileType_tableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last modified date.
        /// </summary>
        public static string LastModifiedDate_fileupload_label {
            get {
                return ResourceManager.GetString("LastModifiedDate_fileupload_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total items count.
        /// </summary>
        public static string PagesCount_label {
            get {
                return ResourceManager.GetString("PagesCount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtf file type.
        /// </summary>
        public static string RtfFileName {
            get {
                return ResourceManager.GetString("RtfFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select files.
        /// </summary>
        public static string SelectFiles_fileupload_label {
            get {
                return ResourceManager.GetString("SelectFiles_fileupload_label", resourceCulture);
            }
        }
    }
}
